name: .NET

on:
  push:
  workflow_dispatch:
    inputs:
      debug_enabled:
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false
jobs:
  build:
    runs-on: windows-2019
    steps:
      - name: checkout
        uses: actions/checkout@v2        
      - name: install
        run: | 
          choco install gitversion.portable -y
          gitversion /l console /output buildserver
          choco install GitReleaseNotes.Portable
          pip install codecov
      - name: before-build
        run: |
          nuget restore
      - name: build-stuff
        run: |
           dotnet build
      - name: upload-artifacts
        uses: actions/upload-artifact@v1
        with:
          name: compiled-protobuf.zip
          path: compiled-protobuf.zip      
      - name: Status update
        if: ${{ github.event_name != 'workflow_dispatch' }}
        uses: ouzi-dev/commit-status-updater@v1.1.0
        with:
          status: "${{ job.status }}"
  workflow-finished:
   needs: [build]
   runs-on: ubuntu-latest
   steps:
     - name: Status update
       if: ${{ github.event_name != 'workflow_dispatch' }}
       uses: ouzi-dev/commit-status-updater@v1.1.0
       with:
         status: "${{ job.status }}"
